export const MUMBAICITYVALUESTATUS = "MUMBAICITYVALUESTATUS";
export const BANGALORECITYVALUESTATUS = "BANGALORECITYVALUESTATUS";
export const DELHICITYVALUESTATUS = "DELHICITYVALUESTATUS";
export const GURGAONCITYVALUESTATUS = "GURGAONCITYVALUESTATUS";
