export const NORTHINDIANVALUESTATUS = "NORTHINDIANVALUESTATUS";
export const SOUTHINDIANVALUESTATUS = "SOUTHINDIANVALUESTATUS";
export const PANASIANVALUESTATUS = "PANASIANVALUESTATUS";
export const CONTINENTALVALUESTATUS = "CONTINENTALVALUESTATUS";
export const BENGALIVALUESTATUS = "BENGALIVALUESTATUS";
export const NORTHINDIANCHINESEVALUESTATUS = "NORTHINDIANCHINESEVALUESTATUS";
export const NORTHINDIANCONTIVALUESTATUS = "NORTHINDIANCONTIVALUESTATUS";
export const MULTICUISINEVALUESTATUS = "MULTICUISINEVALUESTATUS";
