export const BIRTHDAYPARTYVALUESTATUS = "BIRTHDAYPARTYVALUESTATUS";
export const HOUSEPARTYVALUESTATUS = "HOUSEPARTYVALUESTATUS";
export const HOUSEWARMINGVALUESTATUS = "HOUSEWARMINGVALUESTATUS";
export const PREWEDDINGVALUESTATUS = "PREWEDDINGVALUESTATUS";
export const OFFICEPARTYVALUESTATUS = "OFFICEPARTYVALUESTATUS";
export const OTHERVALUESTATUS = "OTHERVALUESTATUS";
